import { Client, Project, WebSite, Domain, Task, ActivityLog, InternalNote, ChecklistItem } from '../../types';

export const initialChecklistTemplate: ChecklistItem[] = [
  // CLIENTE
  { id: 'chk-1', category: 'CLIENTE', label: 'Datos personales y comerciales', completed: true },
  { id: 'chk-2', category: 'CLIENTE', label: 'Fotografías de alta resolución', completed: true },
  { id: 'chk-3', category: 'CLIENTE', label: 'Biografía y trayectoria profesional', completed: true },
  { id: 'chk-4', category: 'CLIENTE', label: 'Listado de servicios y especialidades', completed: true },
  { id: 'chk-5', category: 'CLIENTE', label: 'Redes sociales y enlaces de contacto', completed: true },
  { id: 'chk-6', category: 'CLIENTE', label: 'Información de ubicación y horarios', completed: true },
  // DISEÑO
  { id: 'chk-7', category: 'DISEÑO', label: 'Referencias visuales y estética acordada', completed: true },
  { id: 'chk-8', category: 'DISEÑO', label: 'Definición de paleta cromática y tipografías', completed: true },
  { id: 'chk-9', category: 'DISEÑO', label: 'Estructura wireframe y secciones', completed: true },
  { id: 'chk-10', category: 'DISEÑO', label: 'Diseño editorial aprobado por cliente', completed: true },
  // DESARROLLO
  { id: 'chk-11', category: 'DESARROLLO', label: 'Maquetación responsive mobile-first', completed: true },
  { id: 'chk-12', category: 'DESARROLLO', label: 'Configuración SEO on-page y OpenGraph', completed: true },
  { id: 'chk-13', category: 'DESARROLLO', label: 'Optimización de imágenes (WebP/AVIF)', completed: true },
  { id: 'chk-14', category: 'DESARROLLO', label: 'Formulario de contacto y canal WhatsApp directo', completed: true },
  { id: 'chk-15', category: 'DESARROLLO', label: 'Integración analítica y scripts mínimos', completed: true },
  // PUBLICACIÓN
  { id: 'chk-16', category: 'PUBLICACIÓN', label: 'Repositorio GitHub privado configurado', completed: true },
  { id: 'chk-17', category: 'PUBLICACIÓN', label: 'Pipeline CI/CD en Cloudflare Pages', completed: true },
  { id: 'chk-18', category: 'PUBLICACIÓN', label: 'Delegación DNS en NIC Argentina / Registrar', completed: true },
  { id: 'chk-19', category: 'PUBLICACIÓN', label: 'Certificado SSL/HTTPS verificado', completed: true },
  { id: 'chk-20', category: 'PUBLICACIÓN', label: 'Prueba de carga y rendimiento Core Web Vitals', completed: true },
  { id: 'chk-21', category: 'PUBLICACIÓN', label: 'Entrega final y ficha operativa archivada', completed: true },
];

export const initialClients: Client[] = [
  {
    id: 'TRAY-00001',
    fullName: 'Juan Pérez',
    commercialName: 'Juan Pérez Arquitectura',
    profession: 'Arquitecto',
    email: 'juan@juanperez.com.ar',
    whatsapp: '+54 9 351 555-0192',
    instagram: '@juanperez.arqui',
    linkedin: 'linkedin.com/in/juanperez-arq',
    city: 'Córdoba',
    country: 'Argentina',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    createdAt: '2026-03-10',
    status: 'Activo',
    lastContact: '2026-08-20',
    
    specialties: ['Arquitectura Residencial', 'Diseño Sustentable', 'Dirección de Obra', 'Remodelaciones'],
    bio: 'Arquitecto con más de 12 años de trayectoria liderando proyectos residenciales y comerciales en la región centro del país. Enfoque centrado en la luz natural, la materialidad noble y la eficiencia energética.',
    shortDescription: 'Estudio de arquitectura y diseño contemporáneo con base en Córdoba.',
    experienceSummary: '12 años de experiencia independiente y ex socio en Estudio Nómade.',
    educationSummary: 'Facultad de Arquitectura, Urbanismo y Diseño (UNC) — 2014',
    locationDetails: 'Av. Rafael Núñez 4200, Cerro de las Rosas, Córdoba',
    workingHours: 'Lunes a Viernes 09:00 a 18:00 hs',

    contractedProduct: 'Web Identidad & Portfolio Pro',
    price: '$450 USD',
    paymentMethod: 'Transferencia Bancaria',
    contractDate: '2026-03-10',
    paymentStatus: 'Al día',
    renewalDate: '2027-03-10',
    commercialNotes: 'Plan anual con hosting y mantenimiento técnico incluido. Muy puntual en pagos.',

    primaryDomain: 'juanperez.com.ar',
    domainRegistrar: 'NIC Argentina',
    domainExpiration: '2027-09-15',
    dnsNameservers: ['anna.ns.cloudflare.com', 'george.ns.cloudflare.com'],
    nicDelegationStatus: 'Delegado y Verificado',
    nicAuthCode: '',
    cloudflareProject: 'trayectoria-juan-perez',
    cloudflareZoneId: 'cf-zone-9a8b7c6d5e',
    productionUrl: 'https://juanperez.com.ar',
    tempPreviewUrl: 'https://juanperez-preview.pages.dev',
    githubRepoName: 'trayectoria/juanperez-arqui',
    githubRepoUrl: 'https://github.com/trayectoria-internal/juanperez-arqui',
    framework: 'Astro + Tailwind CSS',
    deploymentStatus: 'Producción activa (Cloudflare Pages)',

    content: {
      identity: {
        name: 'Juan Pérez Arquitectura',
        profession: 'Arquitecto & Diseñador Urbano',
        photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
        colors: ['#1C1917', '#E7E5E4', '#D97706'],
        fonts: 'Plus Jakarta Sans + Instrument Serif',
        isComplete: true,
      },
      presentation: {
        bio: 'Creamos espacios que respiran. Creemos en la arquitectura que perdura a través del diálogo sincero entre el entorno, los materiales y la vida cotidiana.',
        shortDescription: 'Arquitectura con identidad contemporánea y sensibilidad constructiva.',
        mainSlogan: 'Espacios que trascienden el tiempo y habitan el paisaje.',
        isComplete: true,
      },
      services: {
        items: [
          { id: 's1', name: 'Proyecto de Vivienda Unifamiliar', description: 'Diseño integral desde croquis preliminares hasta planos ejecutivos y cómputo métrico.', price: 'A convenir por m2' },
          { id: 's2', name: 'Dirección Técnica de Obra', description: 'Supervisión constante in-situ, control de calidad, proveedores y cronograma.', price: 'Honorarios CAPC' },
          { id: 's3', name: 'Reformas e Interiorismo', description: 'Reconfiguración espacial, interiorismo a medida y selección de acabados.', price: 'Desde $120.000 ARS' },
        ],
        isComplete: true,
      },
      education: {
        items: [
          { id: 'e1', career: 'Arquitecto', institution: 'Universidad Nacional de Córdoba (UNC)', year: '2014' },
          { id: 'e2', career: 'Posgrado en Eficiencia Energética', institution: 'Universidad Torcuato Di Tella', year: '2019' },
        ],
        isComplete: true,
      },
      experience: {
        items: [
          { id: 'exp1', company: 'Juan Pérez Arquitectura', role: 'Titular / Director de Proyecto', description: 'Más de 35 viviendas construidas en Córdoba y alrededores.', year: '2018 - Presente' },
          { id: 'exp2', company: 'Estudio Nómade', role: 'Arquitecto Proyectista Senior', description: 'Coordinación de concursos y obras residenciales.', year: '2014 - 2018' },
        ],
        isComplete: true,
      },
      contact: {
        whatsapp: '+54 9 351 555-0192',
        email: 'juan@juanperez.com.ar',
        instagram: '@juanperez.arqui',
        linkedin: 'linkedin.com/in/juanperez-arq',
        location: 'Córdoba, Argentina',
        googleMapsUrl: 'https://maps.google.com/?q=Cerro+de+las+Rosas+Cordoba',
        schedule: 'Lunes a Viernes 09:00 - 18:00',
        isComplete: true,
      },
      portfolio: {
        items: [
          { id: 'p1', title: 'Casa La Cuesta', description: 'Vivienda de 340m2 en terreno con pendiente natural pronunciada y vistas a las sierras.', imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=80', url: 'https://juanperez.com.ar/proyectos/casa-la-cuesta' },
          { id: 'p2', title: 'Refugio Uritorco', description: 'Hormigón a la vista, piedra del lugar y carpinterías de doble vidriado hermético.', imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&auto=format&fit=crop&q=80', url: 'https://juanperez.com.ar/proyectos/refugio-uritorco' },
        ],
        isComplete: true,
      },
    },
  },
  {
    id: 'TRAY-00002',
    fullName: 'María González',
    commercialName: 'González Creative Studio',
    profession: 'Diseñadora Visual & Branding',
    email: 'maria@gonzalezdesign.com',
    whatsapp: '+54 9 11 4402-8819',
    instagram: '@gonzalez.studio',
    linkedin: 'linkedin.com/in/mariagonzalez-design',
    city: 'Buenos Aires',
    country: 'Argentina',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    createdAt: '2026-06-15',
    status: 'En producción',
    lastContact: '2026-08-27',
    
    specialties: ['Brand Identity', 'Diseño Tipográfico', 'Estrategia de Marca', 'Packaging'],
    bio: 'Directora de arte y diseñadora especializada en construir identidades con narrativa de marca sólida para estudios, marcas de moda y empresas culturales.',
    shortDescription: 'Estudio de diseño visual y dirección de arte con enfoque editorial.',
    experienceSummary: '8 años de experiencia en agencias internacionales y estudio boutique independiente.',
    educationSummary: 'Licenciatura en Diseño Gráfico (FADU - UBA) — 2017',
    locationDetails: 'Palermo Soho, Ciudad Autónoma de Buenos Aires',
    workingHours: 'Lunes a Jueves 10:00 a 17:00 hs',

    contractedProduct: 'Sitio Web Editorial + Portfolio Dinámico',
    price: '$550 USD',
    paymentMethod: 'Stripe / Cripto USDT',
    contractDate: '2026-06-15',
    paymentStatus: 'Al día',
    renewalDate: '2027-06-15',
    commercialNotes: '50% anticipo recibido, 50% contra entrega final de la web.',

    primaryDomain: 'mariagonzalez.design',
    domainRegistrar: 'Cloudflare Registrar',
    domainExpiration: '2026-10-05',
    cloudflareProject: 'trayectoria-maria-gonzalez',
    productionUrl: '',
    tempPreviewUrl: 'https://maria-gonzalez-preview.pages.dev',
    githubRepoName: 'trayectoria/maria-gonzalez-studio',
    githubRepoUrl: 'https://github.com/trayectoria-internal/maria-gonzalez-studio',
    framework: 'Next.js + Tailwind CSS',
    deploymentStatus: 'En staging / Preview disponible',

    content: {
      identity: {
        name: 'González Creative Studio',
        profession: 'Directora de Arte & Brand Designer',
        photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
        colors: ['#09090B', '#FAFAFA', '#6366F1'],
        fonts: 'Neue Montreal + Editorial New',
        isComplete: true,
      },
      presentation: {
        bio: 'Ayudamos a marcas contemporáneas a encontrar una voz gráfica inconfundible mediante síntesis visual y rigor tipográfico.',
        shortDescription: 'Identidades de marca con criterio estético internacional.',
        mainSlogan: 'Diseño donde cada detalle responde a una intención clara.',
        isComplete: true,
      },
      services: {
        items: [
          { id: 's21', name: 'Identidad Visual Integral', description: 'Manual de marca, paleta, tipografía, papelería y activos digitales.', price: 'Desde $800 USD' },
          { id: 's22', name: 'Dirección de Arte & Campañas', description: 'Concepto visual, curaduría fotográfica y lineamientos de producción.', price: 'Por proyecto' },
        ],
        isComplete: true,
      },
      education: {
        items: [
          { id: 'e21', career: 'Lic. en Diseño Gráfico', institution: 'FADU - UBA', year: '2017' },
        ],
        isComplete: true,
      },
      experience: {
        items: [
          { id: 'exp21', company: 'González Studio', role: 'Fundadora', description: 'Proyectos para Argentina, España y México.', year: '2020 - Presente' },
        ],
        isComplete: true,
      },
      contact: {
        whatsapp: '+54 9 11 4402-8819',
        email: 'maria@gonzalezdesign.com',
        instagram: '@gonzalez.studio',
        linkedin: 'linkedin.com/in/mariagonzalez-design',
        location: 'Buenos Aires, Argentina',
        isComplete: true,
      },
      portfolio: {
        items: [
          { id: 'p21', title: 'Atelier Nómada', description: 'Rebranding para galería de arte contemporáneo.', imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80' },
        ],
        isComplete: false, // Incomplete: missing 2nd and 3rd case study descriptions
      },
    },
  },
  {
    id: 'TRAY-00003',
    fullName: 'Carlos Rodríguez',
    commercialName: 'Estudio Jurídico Rodríguez & Asoc.',
    profession: 'Abogado Especialista',
    email: 'contacto@estudiorodriguez.ar',
    whatsapp: '+54 9 341 622-9011',
    instagram: '',
    linkedin: 'linkedin.com/in/carlos-rodriguez-abogado',
    city: 'Rosario',
    country: 'Argentina',
    photoUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop&q=80',
    createdAt: '2026-08-05',
    status: 'Contactado',
    lastContact: '2026-08-28',
    
    specialties: ['Derecho Corporativo', 'Contratos Comerciales', 'Propiedad Intelectual', 'Litigios'],
    bio: 'Abogado con más de 18 años de asesoramiento a pymes y empresas en Santa Fe y la región litoral. Asesor legal permanente y docente universitario.',
    shortDescription: 'Asesoramiento legal corporativo y estratégico para empresas.',
    experienceSummary: '18 años de ejercicio ininterrumpido en la matrícula.',
    educationSummary: 'Facultad de Derecho (UNR) — 2007',
    locationDetails: 'Bv. Oroño 850, Rosario, Santa Fe',
    workingHours: 'Lunes a Viernes 08:30 a 16:30 hs',

    contractedProduct: 'Web Institucional Corporativa',
    price: '$380 USD',
    paymentMethod: 'Transferencia Bancaria',
    contractDate: '2026-08-05',
    paymentStatus: 'Pendiente',
    renewalDate: '2027-08-05',
    commercialNotes: 'Esperando confirmación del presupuesto final y firma del alta.',

    primaryDomain: 'estudiorodriguez.ar',
    domainRegistrar: 'NIC Argentina',
    domainExpiration: '2026-09-18', // Expiring soon (<30 days!)
    dnsNameservers: ['dina.ns.cloudflare.com', 'luke.ns.cloudflare.com'],
    nicDelegationStatus: 'Pendiente de Delegación en NIC',
    nicAuthCode: 'TAD-TR-994821',
    cloudflareProject: 'trayectoria-carlos-rodriguez',
    cloudflareZoneId: 'cf-zone-1b2c3d4e5f',
    productionUrl: '',
    tempPreviewUrl: '',
    githubRepoName: 'trayectoria/estudio-rodriguez',
    githubRepoUrl: 'https://github.com/trayectoria-internal/estudio-rodriguez',
    framework: 'Astro + Tailwind CSS',
    deploymentStatus: 'No inicializado',

    content: {
      identity: {
        name: 'Estudio Jurídico Rodríguez',
        profession: 'Abogados & Consultores Corporativos',
        colors: ['#0F172A', '#F8FAFC', '#94A3B8'],
        fonts: 'Cinzel + Inter',
        isComplete: false,
      },
      presentation: {
        bio: 'Solvencia jurídica y agilidad estratégica para la protección patrimonial y comercial de su empresa.',
        shortDescription: 'Asesoramiento legal riguroso y transparente.',
        mainSlogan: 'Seguridad jurídica para el crecimiento de su negocio.',
        isComplete: true,
      },
      services: {
        items: [
          { id: 's31', name: 'Asesoría Empresarial Preventiva', description: 'Auditoría de riesgos, compliance y redacción contractual.', price: 'Abono mensual' },
        ],
        isComplete: false,
      },
      education: {
        items: [
          { id: 'e31', career: 'Abogado', institution: 'Universidad Nacional de Rosario (UNR)', year: '2007' },
        ],
        isComplete: true,
      },
      experience: {
        items: [],
        isComplete: false,
      },
      contact: {
        whatsapp: '+54 9 341 622-9011',
        email: 'contacto@estudiorodriguez.ar',
        location: 'Rosario, Santa Fe, Argentina',
        isComplete: true,
      },
      portfolio: {
        items: [],
        isComplete: false,
      },
    },
  },
];

export const initialProjects: Project[] = [
  {
    id: 'TRAY-00001-P01',
    clientId: 'TRAY-00001',
    clientName: 'Juan Pérez',
    name: 'Web Identidad & Portfolio Arquitectura',
    projectType: 'Sitio Web Completo + Dominio',
    status: 'Publicado',
    startDate: '2026-03-10',
    estimatedDeliveryDate: '2026-04-05',
    realDeliveryDate: '2026-03-28',
    price: '$450 USD',
    responsible: 'Operaciones Trayectoria',
    notes: 'Proyecto entregado con éxito y con excelente retroalimentación. Dominio delegado y DNS en Cloudflare.',
    checklist: initialChecklistTemplate.map(item => ({ ...item, completed: true })),
    createdAt: '2026-03-10',
  },
  {
    id: 'TRAY-00002-P01',
    clientId: 'TRAY-00002',
    clientName: 'María González',
    name: 'Portfolio Studio & Dirección de Arte',
    projectType: 'Sitio Web Editorial',
    status: 'En revisión',
    startDate: '2026-06-15',
    estimatedDeliveryDate: '2026-09-05',
    price: '$550 USD',
    responsible: 'Operaciones Trayectoria',
    notes: 'Falta que María envíe la última selección de imágenes de alta resolución para el caso de estudio Atelier Nómada.',
    checklist: initialChecklistTemplate.map(item => {
      if (item.category === 'PUBLICACIÓN') return { ...item, completed: false };
      if (item.id === 'chk-14' || item.id === 'chk-15') return { ...item, completed: false };
      return { ...item, completed: true };
    }),
    createdAt: '2026-06-15',
  },
  {
    id: 'TRAY-00003-P01',
    clientId: 'TRAY-00003',
    clientName: 'Carlos Rodríguez',
    name: 'Web Institucional Estudio Jurídico',
    projectType: 'Sitio Web Corporativo',
    status: 'Esperando contenido',
    startDate: '2026-08-05',
    estimatedDeliveryDate: '2026-09-25',
    price: '$380 USD',
    responsible: 'Operaciones Trayectoria',
    notes: 'Esperando que complete el formulario de servicios detallados y foto de perfil corporativa.',
    checklist: initialChecklistTemplate.map(item => {
      if (item.category === 'CLIENTE' && (item.id === 'chk-1' || item.id === 'chk-3')) {
        return { ...item, completed: true };
      }
      return { ...item, completed: false };
    }),
    createdAt: '2026-08-05',
  },
];

export const initialWebs: WebSite[] = [
  {
    id: 'TRAY-00001-W01',
    clientId: 'TRAY-00001',
    clientName: 'Juan Pérez',
    projectId: 'TRAY-00001-P01',
    projectName: 'Web Identidad & Portfolio Arquitectura',
    siteName: 'Juan Pérez Arq',
    primaryDomain: 'juanperez.com.ar',
    secondaryDomains: ['www.juanperez.com.ar'],
    productionUrl: 'https://juanperez.com.ar',
    previewUrl: 'https://juanperez-preview.pages.dev',
    githubRepoName: 'trayectoria/juanperez-arqui',
    githubRepoUrl: 'https://github.com/trayectoria-internal/juanperez-arqui',
    cloudflareProject: 'trayectoria-juan-perez',
    status: 'Publicada',
    publishedAt: '2026-03-28',
    lastUpdatedAt: '2026-08-20',
    framework: 'Astro + Tailwind CSS',
    technicalNotes: 'Desplegado en Cloudflare Pages con DNS proxied, SSL Full (Strict) y cache headers optimizados.',
  },
  {
    id: 'TRAY-00002-W01',
    clientId: 'TRAY-00002',
    clientName: 'María González',
    projectId: 'TRAY-00002-P01',
    projectName: 'Portfolio Studio & Dirección de Arte',
    siteName: 'González Creative Studio',
    primaryDomain: 'mariagonzalez.design',
    secondaryDomains: [],
    productionUrl: '',
    previewUrl: 'https://maria-gonzalez-preview.pages.dev',
    githubRepoName: 'trayectoria/maria-gonzalez-studio',
    githubRepoUrl: 'https://github.com/trayectoria-internal/maria-gonzalez-studio',
    cloudflareProject: 'trayectoria-maria-gonzalez',
    status: 'Preview',
    lastUpdatedAt: '2026-08-27',
    framework: 'Next.js + Tailwind CSS',
    technicalNotes: 'Preview activa para revisión con cliente. Pendiente switch a dominio de producción.',
  },
];

export const initialDomains: Domain[] = [
  {
    id: 'TRAY-00001-D01',
    domainName: 'juanperez.com.ar',
    clientId: 'TRAY-00001',
    clientName: 'Juan Pérez',
    domainType: '.com.ar',
    registrar: 'NIC Argentina',
    owner: 'Juan Pérez (CUIT 20-33445566-9)',
    managedBy: 'TRAYECTORIA (Delegación técnica DNS)',
    dnsNameservers: ['anna.ns.cloudflare.com', 'george.ns.cloudflare.com'],
    nicDelegationStatus: 'Delegado y Verificado',
    registeredDate: '2025-09-15',
    expirationDate: '2027-09-15', // More than 60 days
    status: 'Activo',
    notes: 'Dominio de titularidad del cliente con delegación a nameservers de Cloudflare.',
    autoRenew: false,
  },
  {
    id: 'TRAY-00002-D01',
    domainName: 'mariagonzalez.design',
    clientId: 'TRAY-00002',
    clientName: 'María González',
    domainType: 'Otro',
    registrar: 'Cloudflare Registrar',
    owner: 'María González',
    managedBy: 'TRAYECTORIA (Gestión completa)',
    dnsNameservers: ['isla.ns.cloudflare.com', 'walt.ns.cloudflare.com'],
    nicDelegationStatus: 'Delegado y Verificado',
    registeredDate: '2025-10-05',
    expirationDate: '2026-10-05', // ~37 days (Between 30-60 days)
    status: 'Activo',
    notes: 'Registrado en Cloudflare Registrar con DNSSEC activado.',
    autoRenew: true,
  },
  {
    id: 'TRAY-00003-D01',
    domainName: 'estudiorodriguez.ar',
    clientId: 'TRAY-00003',
    clientName: 'Carlos Rodríguez',
    domainType: '.ar',
    registrar: 'NIC Argentina',
    owner: 'Carlos Rodríguez (CUIT 20-28192834-3)',
    managedBy: 'TRAYECTORIA (Asistencia técnica)',
    dnsNameservers: ['dina.ns.cloudflare.com', 'luke.ns.cloudflare.com'],
    nicDelegationStatus: 'Pendiente de Delegación en NIC',
    registeredDate: '2025-09-18',
    expirationDate: '2026-09-18', // ~20 days (< 30 days - URGENTE!)
    status: 'Activo',
    notes: 'Alerta: Vence en menos de 25 días. Contactar para recordatorio de renovación en NIC Argentina.',
    autoRenew: false,
  },
];

export const initialTasks: Task[] = [
  {
    id: 'TASK-001',
    clientId: 'TRAY-00003',
    clientName: 'Carlos Rodríguez',
    projectId: 'TRAY-00003-P01',
    projectName: 'Web Institucional Estudio Jurídico',
    title: 'Enviar recordatorio de renovación de dominio en NIC Argentina',
    description: 'El dominio estudiorodriguez.ar vence el 18/09. Enviar instructivo de pago en TAD/NIC.',
    priority: 'Alta',
    dueDate: '2026-09-02',
    completed: false,
    assignedTo: 'Operaciones Trayectoria',
    createdAt: '2026-08-28',
  },
  {
    id: 'TASK-002',
    clientId: 'TRAY-00002',
    clientName: 'María González',
    projectId: 'TRAY-00002-P01',
    projectName: 'Portfolio Studio & Dirección de Arte',
    title: 'Subir fotografías del caso de estudio Atelier Nómada',
    description: 'Esperando las 4 imágenes en alta resolución que María prometió por WeTransfer.',
    priority: 'Media',
    dueDate: '2026-09-01',
    completed: false,
    assignedTo: 'Operaciones Trayectoria',
    createdAt: '2026-08-26',
  },
  {
    id: 'TASK-003',
    clientId: 'TRAY-00001',
    clientName: 'Juan Pérez',
    projectId: 'TRAY-00001-P01',
    projectName: 'Web Identidad & Portfolio Arquitectura',
    title: 'Revisión semestral de Core Web Vitals y Analytics',
    description: 'Chequear velocidad de carga y funcionamiento del formulario en juanperez.com.ar.',
    priority: 'Baja',
    dueDate: '2026-09-15',
    completed: false,
    assignedTo: 'Operaciones Trayectoria',
    createdAt: '2026-08-20',
  },
];

export const initialActivityLogs: ActivityLog[] = [
  {
    id: 'ACT-001',
    clientId: 'TRAY-00003',
    clientName: 'Carlos Rodríguez',
    type: 'status_change',
    title: 'Estado del cliente actualizado',
    description: 'Carlos Rodríguez pasó a estado Contactado. Se envió el formulario de requerimientos.',
    date: '2026-08-28',
    author: 'Operaciones',
  },
  {
    id: 'ACT-002',
    clientId: 'TRAY-00002',
    clientName: 'María González',
    type: 'preview_sent',
    title: 'URL de Preview enviada al cliente',
    description: 'Se compartió https://maria-gonzalez-preview.pages.dev para revisión y feedback.',
    date: '2026-08-27',
    author: 'Operaciones',
  },
  {
    id: 'ACT-003',
    clientId: 'TRAY-00002',
    clientName: 'María González',
    type: 'change_requested',
    title: 'María González solicitó modificación',
    description: 'Ajustar espaciado entre grilla de proyectos en mobile y cambiar color de acento a índigo sutil.',
    date: '2026-08-26',
    author: 'Cliente',
  },
  {
    id: 'ACT-004',
    clientId: 'TRAY-00001',
    clientName: 'Juan Pérez',
    type: 'web_published',
    title: 'Web publicada exitosamente',
    description: 'Sitio juanperez.com.ar desplegado en Cloudflare Pages con DNS verificado.',
    date: '2026-03-28',
    author: 'Operaciones',
  },
  {
    id: 'ACT-005',
    clientId: 'TRAY-00001',
    clientName: 'Juan Pérez',
    type: 'content_received',
    title: 'Fotografías y textos recibidos',
    description: 'Juan entregó carpetas de Casa La Cuesta y Refugio Uritorco con memoria descriptiva.',
    date: '2026-03-17',
    author: 'Cliente',
  },
];

export const initialInternalNotes: InternalNote[] = [
  {
    id: 'NOTE-001',
    clientId: 'TRAY-00001',
    author: 'Operaciones Trayectoria',
    content: 'Prefiere comunicación directa por WhatsApp en horario de mañana (09 a 12). Muy satisfecho con el resultado.',
    createdAt: '2026-03-12 11:30',
  },
  {
    id: 'NOTE-002',
    clientId: 'TRAY-00001',
    author: 'Operaciones Trayectoria',
    content: 'Pidió no utilizar fotografías de stock bajo ningún concepto. Todas las fotos de obra son de fotógrafos locales.',
    createdAt: '2026-03-15 16:45',
  },
  {
    id: 'NOTE-003',
    clientId: 'TRAY-00002',
    author: 'Operaciones Trayectoria',
    content: 'Es muy detallista con la tipografía y kerning. Validar siempre los tamaños de fuente antes de enviar versión de preview.',
    createdAt: '2026-06-18 10:15',
  },
  {
    id: 'NOTE-004',
    clientId: 'TRAY-00003',
    author: 'Operaciones Trayectoria',
    content: 'Contactado a través de recomendación de Juan Pérez. Busca transmitir seriedad y trayectoria institucional sin caer en plantillas anticuadas.',
    createdAt: '2026-08-06 09:00',
  },
];
